Repository thoth-station/graph-sync-job, pull requests merged in 2018-12, with the labels that each got.

#124 Move from cronjob to event driven jobs
  openshift/cronJob-template.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/L

#127 Move from argument to option so click handles env vars correctly
  app.py
Labels: size/S, size/XS

#125 Automatic update of dependency prometheus-client from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot

#128 Automatic update of dependency thoth-storages from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#129 Automatic update of dependency thoth-common from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#130 Report Amun API into logs
  app.py
Labels: size/XS

#131 Be graceful with inspection documents syncing
  app.py
Labels: size/XS

#133 Automatic update of dependency thoth-storages from 0.9.4 to 0.9.5
  Pipfile.lock
Labels: bot
