Repository thoth-station/graph-sync-job, pull requests merged in 2018-09, with the labels that each got.

#55 Automatic update of dependency thoth-common from 0.2.5 to 0.2.6
  Pipfile.lock
Labels: bot

#56 Automatic update of dependency thoth-common from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot

#57 Automatic update of dependency thoth-common from 0.2.7 to 0.3.0
  Pipfile.lock
Labels: bot

#60 job metrics
  .coafile
  .gitignore
  CHANGELOG.md
  Makefile
  Pipfile
  Pipfile.lock
  README.rst
  app.py
  conf.py
  observability.md
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: size/XXL

#61 some more docs
  README.rst
  observability.md
  observability.rst
  openshift/cronJob-template.yaml
Labels: size/M

#62 renamed metrics
  app.py
  observability.rst
Labels: size/S

#66 Fix deployment issues
  openshift/cronJob-template.yaml
Labels: size/XS

#67 Automatic update of dependency thoth-common from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot

#68 Automatic update of dependency click from 6.7 to 7.0
  Pipfile.lock
Labels: bot

#70 Automatic update of dependency thoth-common from 0.3.2 to 0.3.5
  Pipfile.lock
Labels: bot

#71 Update README file
  README.rst
Labels: approved, size/M
