Repository thoth-station/graph-sync-job, pull requests merged in 2018-06, with the labels that each got.

#20 set resource limits of BC, DC; relocked Pipfile
  CHANGELOG.md
  Pipfile.lock
  app.py
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
Labels: approved, size/L

#21 Rename THOTH_CEPH_HOST to THOTH_S3_ENDPOINT_URL
  app.py
  openshift/cronJob-template.yaml
Labels: approved, lgtm, size/XS

#23 Automatic update of dependency thoth-storages from 0.0.29 to 0.0.32
  Pipfile.lock
Labels: approved, bot, size/L
