Repository thoth-station/graph-sync-job, pull requests merged in 2018-05, with the labels that each got.

#11 Remove travis, updated Dependencies
  .gitignore
  .travis.yml
  Dockerfile
  Pipfile
  Pipfile.lock
  README.rst
  app.py
  build.sh
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
  requirements.txt
Labels: approved, size/L

#12 Use coala for code checks
  .coafile
  app.py
Labels: approved, size/S

#13 Update thoth-storages
  Pipfile
  Pipfile.lock
Labels: size/L

#14 Add rsyslog logging
  openshift/cronJob-template.yaml
Labels: size/S

#15 Update thoth-common for rsyslog logging
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#17 Automatic update of dependency thoth-common from 0.0.5 to 0.0.6
  Pipfile.lock
Labels: approved, size/XS

#18 Automatic update of dependency thoth-storages from 0.0.25 to 0.0.28
  Pipfile.lock
Labels: approved, size/XS

#19 Automatic update of dependency thoth-storages from 0.0.28 to 0.0.29
  Pipfile.lock
Labels: approved, size/XS
