Repository thoth-station/graph-sync-job, pull requests merged in 2018-07, with the labels that each got.

#22 Automatic update of dependency thoth-common from 0.0.6 to 0.0.9
  Pipfile.lock
Labels: approved, bot, size/S

#25 added a zuul config, removed travis, CHANGELOG!!
  .travis.yml
  .zuul.yaml
  CHANGELOG.md
  app.py
Labels: approved, size/M

#27 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: approved, bot

#29 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#31 Initial dependency lock
  Pipfile.lock
Labels: bot

#32 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#33 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#34 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#36 Automatic update of dependency thoth-storages from 0.0.33 to 0.1.0
  Pipfile.lock
Labels: bot

#38 Template labels
  openshift/buildConfig-template.yaml
  openshift/cronJob-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#39 Automatic update of dependency thoth-storages from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#41 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot
