Repository thoth-station/graph-sync-job, pull requests merged in 2019-05, with the labels that each got.

#183 Automatic update of dependency thoth-storages from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#185 Fix check when syncing provenance-checker documents
  app.py
Labels: size/XS

#184 Always issue force sync in the cluster
  openshift/adviserSyncJob-template.yaml
  openshift/dependencyMonkeySyncJob.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/S

#187 Automatic update of dependency thoth-storages from 0.11.1 to 0.11.2
  Pipfile.lock
Labels: bot

#188 Automatic update of dependency thoth-storages from 0.11.2 to 0.11.3
  Pipfile.lock
Labels: bot

#189 Automatic update of dependency thoth-storages from 0.11.3 to 0.11.4
  Pipfile.lock
Labels: bot

#190 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#192 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.0
  Pipfile.lock
Labels: bot
