Repository thoth-station/graph-sync-job, pull requests merged in 2019-03, with the labels that each got.

#161 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#163 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#164 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#165 fixed webhhok url
  .zuul.yaml
Labels: size/XS

#166 imagestream namespace
  openshift/.inspectionSyncJob-template.yaml.swp
  openshift/adviserSyncJob-template.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: approved, size/L
