Repository thoth-station/graph-sync-job, pull requests merged in 2019-06, with the labels that each got.

#193 Automatic update of dependency thoth-storages from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot

#194 Automatic update of dependency thoth-common from 0.8.7 to 0.8.11
  Pipfile.lock
Labels: bot

#196 Automatic update of dependency prometheus-client from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#197 Update zuul pipeline to use the new version trigger build job
  .zuul.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#199 Automatic update of dependency thoth-common from 0.8.11 to 0.9.0
  Pipfile.lock
Labels: bot

#198 Standardize variables and explicitly set the collection of metrics
  app.py
  openshift/adviserSyncJob-template.yaml
Labels: approved, size/S, size/XS

#200 Let cleanup job clean all graph syncs after 1 hour
  openshift/adviserSyncJob-template.yaml
  openshift/dependencyMonkeySyncJob.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: approved, size/S

#201 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#202 Automatic update of dependency thoth-common from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#203 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot

#204 Add missing import
  app.py
Labels: approved, size/XS

#206 Increase backoff limit for syncs due to transactions
  openshift/adviserSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: approved, size/XS

#207 Automatic update of dependency thoth-storages from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot
