Repository thoth-station/graph-sync-job, pull requests merged in 2019-07, with the labels that each got.

#205 Modify metrics
  app.py
Labels: approved, size/L

#209 Fix syntax and undefined variable errors
  app.py
Labels: approved, size/XS

#213 Corrected wrong attributes
  app.py
Labels: approved, size/S

#212 Introduce template for graph sync multiple
  openshift/syncJob-template.yaml
Labels: approved, size/L

#210 Introduce retry mechanism for job
  app.py
Labels: approved, size/L

#214 Automatic update of dependency thoth-storages from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot

#215 Automatic update of dependency thoth-storages from 0.14.4 to 0.14.5
  Pipfile.lock
Labels: bot

#216 Automatic update of dependency thoth-storages from 0.14.5 to 0.14.6
  Pipfile.lock
Labels: bot

#217 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#218 Automatic update of dependency thoth-storages from 0.14.6 to 0.14.7
  Pipfile.lock
Labels: bot

#219 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#221 Automatic update of dependency thoth-storages from 0.14.7 to 0.14.8
  Pipfile.lock
Labels: bot

#223 Add CODEOWNERS file and standard GitHub templates
  .coafile
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/M

#225 Fix syntax error
  app.py
Labels: approved, size/XS

#226 Automatic update of dependency thoth-common from 0.9.3 to 0.9.4
  Pipfile.lock
Labels: bot

#227 Automatic update of dependency thoth-storages from 0.14.8 to 0.15.0
  Pipfile.lock
Labels: bot

#229 Automatic update of dependency thoth-storages from 0.15.0 to 0.15.1
  Pipfile.lock
Labels: bot

#232 Automatic update of dependency thoth-storages from 0.15.1 to 0.15.2
  Pipfile.lock
Labels: bot

#233 syncing package analyzer results
  app.py
  openshift/packageExtractSyncJob-template.yaml
  openshift/syncJob-template.yaml
Labels: approved, do-not-merge/work-in-progress, size/M

#235 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#228 Added time, namespace label
  app.py
  openshift/adviserSyncJob-template.yaml
  openshift/dependencyMonkeySyncJob.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
  openshift/syncJob-template.yaml
Labels: approved, size/L, size/M, size/S

#238 Automatic update of dependency thoth-storages from 0.15.2 to 0.16.0
  Pipfile.lock
Labels: bot

#240 Readme typo
  README.rst
Labels: approved, size/XS

#241 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#242 Fix template for dependency monkey graph sync job
  openshift/dependencyMonkeySyncJob.yaml
Labels: approved, size/S

#243 Correct variable
  app.py
Labels: approved, size/XS

#244 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
