Repository thoth-station/graph-sync-job, pull requests merged in 2019-11, with the labels that each got.

#306 Remove ttl configuration for cleanup
  openshift/syncJob-template.yaml
Labels: approved, size/XS

#307 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#308 Create configuration option to explictly state documents are from a local dir
  app.py
Labels: approved, size/S

#309 just a new version
  app.py
Labels: approved, size/XS

#310 Increase backoff limit for failing graph syncs
  openshift/syncJob-template.yaml
Labels: approved, size/XS

#312 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#313 Manual update of dependencies
  Pipfile.lock
Labels: approved, size/L

#315 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#316 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#317 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#318 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.21
  Pipfile.lock
Labels: bot, size/M

#319 Automatic update of dependency thoth-storages from 0.19.21 to 0.19.22
  Pipfile.lock
Labels: bot, size/XS

#320 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#321 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#322 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#323 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/M

#325 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M
