Repository thoth-station/graph-sync-job, pull requests merged in 2019-04, with the labels that each got.

#167 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#168 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#169 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#170 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#172 Automatic update of dependency autopep8 from 1.4.3 to 1.4.4
  Pipfile.lock
Labels: bot

#174 Automatic update of dependency thoth-storages from 0.9.7 to 0.10.0
  Pipfile.lock
Labels: bot

#175 Remove JanusGraph specific bits
  README.rst
Labels: approved, size/XS

#176 Adjust adviser graph-sync-job template for Dgraph
  openshift/adviserSyncJob-template.yaml
Labels: approved, size/S

#173 Provide job for syncing dependency monkey documents
  app.py
  openshift/dependencyMonkeySyncJob.yaml
Labels: approved, size/L

#181 Automatic update of dependency thoth-storages from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot

#180 Adjust graph-sync-job of solver documents for Dgraph
  openshift/solverSyncJob-template.yaml
Labels: size/S

#179 Adjust graph-sync for provenance-checker
  openshift/provenanceCheckerSyncJob-template.yaml
Labels: approved, size/S

#177 Adjust graph-sync-job for inspections to use Dgraph
  openshift/inspectionSyncJob-template.yaml
Labels: approved, size/S

#178 Adjust graph-sync-job for package-extract
  openshift/packageExtractSyncJob-template.yaml
Labels: approved, size/S
