Repository thoth-station/graph-sync-job, pull requests merged in 2019-09, with the labels that each got.

#266 Switch from Dgraph to PostgreSQL in deployment
  openshift/adviserSyncJob-template.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageAnalyzerSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
  openshift/syncJob-template.yaml
Labels: approved, size/L

#267 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#265 Updated the README
  README.rst
Labels: approved, human_intervention_required, needs-rebase, size/S

#268 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#269 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#270 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#274 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#276 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#277 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#278 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#280 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#281 Add label to distinguish adviser graph syncs
  openshift/adviserSyncJob-template.yaml
Labels: approved, size/XS

#282 Update thoth-python quickly
  Pipfile.lock
Labels: size/XS

#283 use postgresql hostname from thoth configmap
  openshift/adviserSyncJob-template.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageAnalyzerSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
  openshift/syncJob-template.yaml
Labels: approved, size/M

#284 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#285 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#286 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot
