Repository thoth-station/graph-sync-job, pull requests merged in 2019-01, with the labels that each got.

#135 renamed the templates
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/S

#137 Fix generate name in template
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/XS

#138 Remove unused import
  app.py
Labels: size/XS

#140 Do not be graceful with syncs
  app.py
Labels: size/XS

#141 Add job identifier into templates
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/S

#144 Give inspection syncs ability to omit Ceph or graph database
  app.py
  openshift/inspectionSyncJob-template.yaml
Labels: size/M

#142 Propagate document ids down to pods
  openshift/.inspectionSyncJob-template.yaml.swp
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/XS

#143 Give sync 2 hours, restart it if not finished
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/S

#145 Automatic update of dependency thoth-common from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#147 Introduce template for adviser graph syncs
  openshift/adviserSyncJob-template.yaml
Labels: size/L
