Repository thoth-station/graph-sync-job, pull requests merged in 2019-08, with the labels that each got.

#245 Standardize labels for metrics
  openshift/adviserSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
Labels: approved, size/XS

#246 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: approved, bot

#247 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#248 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#249 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#250 Automatic update of dependency recommonmark from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#252 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#253 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#254 Automatic update of dependency thoth-common from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#255 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#256 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#257 Added config
  .thoth.yaml
Labels: approved, size/S

#258 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M
