Repository thoth-station/graph-sync-job, pull requests merged in 2019-10, with the labels that each got.

#288 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#287 [WIP] Simplify handling of syncs
  app.py
  openshift/adviserSyncJob-template.yaml
  openshift/dependencyMonkeySyncJob.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageAnalyzerSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: approved, size/XXL

#289 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#290 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#293 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#295 Hotfix for the var force_sync
  app.py
  openshift/syncJob-template.yaml
Labels: size/S

#296 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#297 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#298 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/syncJob-template.yaml
Labels: approved, size/S

#300 Fix referencing graph sync types
  openshift/syncJob-template.yaml
Labels: approved, size/XS

#301 Fix referencing graph sync types.
  openshift/syncJob-template.yaml
Labels: approved, size/XS

#302 Template metadata label graph-sync-type is not required
  openshift/syncJob-template.yaml
Labels: approved, size/XS

#303 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#304 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
