Repository thoth-station/graph-sync-job, pull requests merged in 2019-12, with the labels that each got.

#326 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/M

#327 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#329 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/S

#330 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/M

#331 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#332 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#334 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M
