Repository thoth-station/graph-sync-job, pull requests merged in 2019-02, with the labels that each got.

#150 Update year in sources
  app.py
  conf.py
Labels: size/XS

#149 Implement adviser documents syncing logic in graph syncs
  app.py
Labels: size/M

#152 Correctly error out if there are some issues
  app.py
Labels: size/XS

#153 Automatic update of dependency sphinx-rtd-theme from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#154 Add graph-sync-type to labels for sync type specific queries
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: size/XS

#156 Automatic update of dependency thoth-storages from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#157 Automatic update of dependency thoth-common from 0.6.0 to 0.7.1
  Pipfile.lock
Labels: approved, bot

#158 Introduce graph-sync-provenance-checker
  app.py
  openshift/provenanceCheckerSyncJob-template.yaml
Labels: size/L

#159 Clean up syncs, let sync jobs be present for at least one hour
  openshift/adviserSyncJob-template.yaml
  openshift/inspectionSyncJob-template.yaml
  openshift/packageExtractSyncJob-template.yaml
  openshift/provenanceCheckerSyncJob-template.yaml
  openshift/solverSyncJob-template.yaml
Labels: approved, size/S

#160 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot
