Repository thoth-station/graph-sync-job, pull requests merged in 2020-07, with the labels that each got.

#443 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/L

#444 Automatic update of dependency thoth-common from 0.13.13 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/L

#446 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#449 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/L

#451 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/L

#452 Release of version 0.6.3
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#455 include ci config file and remove migrated files
  .aicoe-ci.yaml
  workflows/templates/sync-template.yaml
Labels: approved, size/L

#457 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/S

#458 Automatic update of dependency thoth-common from 0.15.0 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/S

#459 Release of version 0.7.0
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS

#462 Release of version 0.7.1
  CHANGELOG.md
  version.py
Labels: approved, bot, size/XS
