Repository thoth-station/graph-sync-job, pull requests merged in 2020-05, with the labels that each got.

#415 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#416 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/L

#419 Feature: service version string
  .github/CODEOWNERS
  .pre-commit-config.yaml
  app.py
  conf.py
  observability.rst
  version.py
Labels: approved, size/L

#420 Release of version 0.6.1
  CHANGELOG.md
  version.py
Labels: bot, size/L

#422 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#423 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/M

#424 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#425 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#426 Automatic update of dependency prometheus-client from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/S

#427 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#428 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/S

#429 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/XS

#430 Automatic update of dependency autopep8 from 1.5.2 to 1.5.3
  Pipfile.lock
Labels: bot, size/S
