Repository thoth-station/graph-sync-job, pull requests merged in 2020-06, with the labels that each got.

#433 Release of version 0.6.2
  CHANGELOG.md
  version.py
Labels: bot, size/S

#435 Remove registry related bits
  workflows/templates/sync-template.yaml
Labels: approved

#436 Remove OpenShift templates as they are part of thoth-application
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
  openshift/syncJob-template.yaml
Labels: approved, size/L

#437 Automatic update of dependency thoth-storages from 0.22.12 to 0.24.0
  Pipfile.lock
Labels: approved, bot, size/L

#438 Automatic update of dependency thoth-common from 0.13.8 to 0.13.13
  Pipfile.lock
Labels: approved, bot, size/L

#440 Automatic update of dependency sphinx-rtd-theme from 0.4.3 to 0.5.0
  Pipfile.lock
Labels: approved, bot, size/L

#442 Fix trailing whitespace
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, size/XS
