Repository thoth-station/graph-sync-job, pull requests merged in 2020-03, with the labels that each got.

#382 Automatic update of dependency click from 7.0 to 7.1.1
  Pipfile.lock
Labels: bot, size/M

#383 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/XS

#386 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot, size/L

#387 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.4
  Pipfile.lock
Labels: bot, size/S

#388 Automatic update of dependency thoth-storages from 0.22.4 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS

#389 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/M

#390 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot

#391 Automatic update of dependency thoth-common from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/M

#392 Automatic update of dependency thoth-common from 0.12.2 to 0.12.3
  Pipfile.lock
Labels: bot, size/XS

#393 Automatic update of dependency thoth-common from 0.12.3 to 0.12.4
  Pipfile.lock
Labels: bot, size/S

#394 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.6
  Pipfile.lock
Labels: bot, size/S

#395 Automatic update of dependency thoth-storages from 0.22.6 to 0.22.7
  Pipfile.lock
Labels: bot, size/M

#396 Add WorkflowTemplate for graph-sync to the correct location
  workflows/templates/sync-template.yaml
Labels: approved, size/L

#398 Automatic update of dependency thoth-common from 0.12.4 to 0.12.5
  Pipfile.lock
Labels: bot, size/M
