Repository thoth-station/graph-sync-job, pull requests merged in 2020-12, with the labels that each got.

#514 Update lock for release
  Pipfile.lock
Labels: approved, size/L

#517 fix unstatisfied markers issue for py3.8
  Pipfile.lock
Labels: approved, size/XS

#531 Added corrected Pipfile
  Pipfile
  Pipfile.lock
Labels: approved, size/XL
