Repository thoth-station/graph-sync-job, pull requests merged in 2020-01, with the labels that each got.

#335 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/L

#336 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#337 Happy new year!
  app.py
Labels: approved, size/XS

#338 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/XS

#339 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/S

#340 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#341 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/M

#342 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#343 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#344 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/S

#345 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#346 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/XS

#347 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#348 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#349 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/XS

#350 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/M

#351 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/S

#352 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#353 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/S

#354 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/XS

#355 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#356 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/M

#357 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#358 Automatic update of dependency autopep8 from 1.4.4 to 1.5
  Pipfile.lock
Labels: bot, size/M

#359 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/XS

#360 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/S

#361 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/S

#362 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#363 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/L

#364 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/XS

#365 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#367 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/L

#368 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/M
