Repository thoth-station/graph-sync-job, pull requests merged in 2020-09, with the labels that each got.

#477 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.7
  Pipfile.lock
Labels: approved, bot, size/L

#478 Automatic update of dependency thoth-common from 0.16.1 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/L

#484 Automatic update of dependency thoth-common from 0.18.1 to 0.18.2
  Pipfile.lock
Labels: approved, bot, size/S

#486 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.8
  Pipfile.lock
Labels: approved, bot, size/M

#487 Automatic update of dependency thoth-common from 0.18.2 to 0.18.3
  Pipfile.lock
Labels: bot, size/M

#489 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#491 Release of version 0.7.3
  CHANGELOG.md
  version.py
Labels: approved, bot, size/S

#493 Automatic update of dependency thoth-storages from 0.25.8 to 0.25.10
  Pipfile.lock
Labels: approved, bot, size/M

#494 Automatic update of dependency thoth-common from 0.18.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot

#499 Add @pacospace to .thoth.yaml
  .thoth.yaml
Labels: size/XS

#500 Release of version 0.7.4
  CHANGELOG.md
  version.py
Labels: approved, bot

#502 Automatic update of dependency thoth-storages from 0.25.10 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/M
