Repository thoth-station/graph-sync-job, pull requests merged in 2020-02, with the labels that each got.

#369 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#370 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/S

#371 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#372 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#374 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/M

#373 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#375 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/M

#376 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/XS

#377 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#378 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/S

#379 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/L

#380 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/M

#381 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/M
