Repository thoth-station/graph-sync-job, pull requests merged in 2021-02, with the labels that each got.

#540 Add Kebechet issue templates
  .github/ISSUE_TEMPLATE/kebechet-info.md
  .github/ISSUE_TEMPLATE/kebechet-update.md
Labels: approved, size/S

#545 Add missing templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/kebechet_update.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/M

#544 Simplify sources, use just one module for component
  app.py
  version.py
Labels: approved, size/S

#552 Fix the reference issue of version string
  app.py
Labels: size/XS
