Repository thoth-station/graph-sync-job, pull requests merged in 2023-01, with the labels that each got.

#678 :face_in_clouds: Remove unsupported env var in graph-sync job
  app.py
Labels: approved, size/M, lgtm

#676 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test

#681 :pushpin: Update graph-sync python dependencies
  Pipfile
  Pipfile.lock
Labels: size/XL
